Repository jNaimXIII/Shiritori, pull requests merged in 2023-06, with the labels that each got.

#5 Add User, Game, and Word models
  docs/models.md
Labels: core

#8 add code formatting settings through prettier
  .vscode/.prettierrc
  .vscode/settings.json
  docs/.prettierrc
  docs/models.md
Labels: code quality

#10 Add core game engine
  .gitignore
  apps/engine/.prettierrc
  apps/engine/package.json
  apps/engine/src/main.ts
  apps/engine/tsconfig.json
Labels: core

#18 Add GPL-3.0 license
  LICENSE
Labels: documentation

#16 Update Shiritori Dev Log link
  README.md
Labels: documentation

#19 Remove external model documentation
  docs/models.md
Labels: documentation, help wanted, code quality

#20 Create typescript configuration for engine package
  apps/engine/.gitignore
  apps/engine/package.json
  apps/engine/pnpm-lock.yaml
  apps/engine/src/main.ts
  apps/engine/tsconfig.json
Labels: core, code quality

#21 Added in code documentation for game engine
  apps/engine/src/main.ts
  docs/.prettierrc
Labels: documentation, code quality

#23 fix engine library typescript configuration
  .gitignore
  package.json
  packages/engine/package.json
  packages/engine/tsconfig.json
  packages/engine/tsconfig.module.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: core, code quality

#28 Clean up file
  packages/engine/pnpm-lock.yaml
Labels: code quality

#29 Add api boilerplate code
  apps/api/package.json
  apps/api/src/main.ts
  apps/api/tsconfig.json
  packages/engine/.gitignore
  pnpm-lock.yaml
Labels: core

#30 Add eslint config
  apps/api/.eslintrc.json
  apps/api/package.json
  configs/eslint-config-server/package.json
  configs/eslint-config-server/src/main.js
  configs/eslint-config-shiritori/package.json
  configs/eslint-config-shiritori/src/main.js
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: core, code quality

#33 add dev script to api
  apps/api/package.json
  pnpm-lock.yaml
Labels: core, code quality

#37 update eslint for engine
  packages/engine/.eslintrc.json
  packages/engine/package.json
  packages/engine/src/main.ts
Labels: core, code quality

#40 add eslint commands
  apps/api/.eslintignore
  apps/api/package.json
  package.json
  packages/engine/.eslintignore
  packages/engine/package.json
  pnpm-lock.yaml
  turbo.json
Labels: core, code quality
